// Generated by CoffeeScript 1.7.1
(function() {
  var debugHLLAPI, messages, outPut;

  console.log("Beginning HLLAPI tests...");

  messages = require('./messages.json');

  outPut = function(functionNum, returnCode, dataString) {
    var messageArray, messageObj;
    messageArray = messages.functionMessageArray;
    messageObj = messageArray[functionNum];
    console.log("\n\n[" + Date.toString + "]: Error on Function Name '" + messageObj.name + "'.");
    console.log("\tThis function was called inside:");
    console.log("\tYou passed it the following data: " + dataString);
    console.log("\tHLLAPI returned a return code of: " + returnCode);
    console.log("\tHLLAPI's  message: " + messageObj.message);
    console.log("\tExplaination: " + messageObj.explaination + "\n\n");
  };

  debugHLLAPI = function(mode, functionNum, returnCode, dataString) {
    if (mode) {
      switch (functionNum) {
        case 1:
          return output(1, returnCode, dataString);
      }
    }
  };

  exports.debugHLLAPI = debugHLLAPI;

}).call(this);
