// Generated by CoffeeScript 1.7.1
(function() {
  var cString, connectPresentationSpace, disconnectPresentationSpace, ffi, hllapi, hllapiLib, hlldll, intPtr, ref, sendKey;

  ffi = require('ffi');

  ref = require('ref');

  hlldll = ffi.DynamicLibrary("./hllapi32.dll");

  hllapi = hlldll.get('WinHLLAPI');

  intPtr = ref.refType(ref.types.int32);

  cString = ref.refType(ref.types.CString);

  hllapiLib = ffi.Library('hllapi32', {
    'WinHLLAPI': [intPtr, [intPtr, cString, intPtr, intPtr]]
  });

  connectPresentationSpace = function(presentationSpace) {
    var data_string, function_number, length, ps_position;
    function_number = ref.alloc(ref.types.int32, 1);
    data_string = ref.allocCString(presentationSpace);
    length = ref.alloc(ref.types.int32, 4);
    ps_position = ref.alloc(ref.types.int32, 0);
    hllapiLib.WinHLLAPI(function_number, data_string, length, ps_position);
    return ps_position.deref();
  };

  disconnectPresentationSpace = function() {
    var data_string, function_number, length, ps_position;
    function_number = ref.alloc(ref.types.int32, 2);
    data_string = ref.allocCString('A');
    length = ref.alloc(ref.types.int32, 4);
    ps_position = ref.alloc(ref.types.int32, 0);
    hllapiLib.WinHLLAPI(function_number, data_string, length, ps_position);
    return ps_position.deref();
  };

  sendKey = function(key) {
    var data_string, function_number, length, ps_position;
    function_number = ref.alloc(ref.types.int32, 3);
    data_string = ref.allocCString(key);
    length = ref.alloc(ref.types.int32, key.length);
    ps_position = ref.alloc(ref.types.int32, 0);
    hllapiLib.WinHLLAPI(function_number, data_string, length, ps_position);
    return ps_position.deref();
  };

  console.log(connectPresentationSpace('A'));

  console.log(sendKey("H"));

  console.log(sendKey("I"));

  console.log(disconnectPresentationSpace());

}).call(this);
